### ISSUE TITLE
error when automatic installation

### ISSUE THREAD

**Issue by ppLorins** [egalpin/apt-vim#43]
File "./apt-vim", line 97
    return {k.replace('_', '-'): v for k,v in list(self.__dict__.items())}

this is the err msg , my python version is 2.7

**Comment by egalpin** [comment]
Thanks for logging this. Which OS are you using?

**Comment by egalpin** [comment]
@ppLorins please be sure to update/checkout the latest version of `apt-vim`.  After trying that, let me know if you have any problems :-)

**Comment by alvarojoao** [comment]
I'm getting the same issue.

> curl -sL https://raw.githubusercontent.com/egalpin/apt-vim/master/install.sh | sh

```
Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
  File "./apt-vim", line 97
    return {k.replace('_', '-'): v for k,v in list(self.__dict__.items())}
                                     ^
SyntaxError: invalid syntax
```

OS: CentOS release 6.8 (Final)

**Comment by asilvino** [comment]
I had this problem but I used the python3 and everything worked as expected!

Thanks! Great project.

**Comment by egalpin** [comment]
thanks @alvarojoao, I appreciate the kind words :-)  Thanks for reporting your findings.  I thought I had most things compatible with python2 and python3, but perhaps I need to revisit. This is valuable info to help me hunt down compatibility issues!
